version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: contents-crawler
      POSTGRES_PASSWORD: contents-crawler2025
    ports:
      - '5432:5432'

volumes:
  postgres_data:
