name: Deploy

on:
  schedule:
    - cron: '0 3-9 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-server:
    name: Contents Crawler Server Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
          project: aptheparker/free
          stage: main
          yaml: >
            name: contents-crawler-server

            app: python@3.9

            options:
              env:
                - name: DATABASE_URL
                  value: ${{ secrets.DATABASE_URL }}
              ports: "5001"
              start: gunicorn -b 0.0.0.0:5001 app:app
              buildenv: []

            context:
              git:
                url: https://github.com/${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: python-flask

  deploy-db:
    name: Contents Crawler DB Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
          project: aptheparker/free
          stage: main
          yaml: |
            name: contents-crawler-db

            app: postgresql@16

            options:
              rootusername: contents-crawler
              rootpassword: ${{ secrets.DB_ROOT_PASSWORD }}
              database: postgres

            context:
              preset: postgresql
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
